# BACKBONE : "VggNet", "InceptionNet"
BACKBONE: "InceptionNet"
# 16 or 8
ANCHOR_WIDTH: 16
ANCHOR_HEIGHT: [11, 16, 23, 33, 48, 68, 97, 139, 198, 283]
CLASSES_NUM: 2
CLASSES_NAME: ["backgroung", "text"]
USE_GPU_NMS: True
INPUT_NORMALIZATION: False
TRAIN:
  restore: 0
  max_steps: 50000
  SOLVER: Adam
  OHEM: False
  RPN_BATCHSIZE: 300
  BATCH_SIZE: 300
  LOG_IMAGE_ITERS: 100
  DISPLAY: 10
  SNAPSHOT_ITERS: 1000
  HAS_RPN: True
  LEARNING_RATE: 0.00001
  MOMENTUM: 0.9
  GAMMA: 0.1
  STEPSIZE: 30000
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
  PRECLUDE_HARD_SAMPLES: True
  BBOX_INSIDE_WEIGHTS: [0, 1, 0, 1]
  RPN_BBOX_INSIDE_WEIGHTS: [0, 1, 0, 1]
  RPN_POSITIVE_WEIGHT: -1.0
  FG_FRACTION: 0.3
  WEIGHT_DECAY: 0.0005
  RANDOM_DOWNSAMPLE: False
TEST:
  HAS_RPN: True
  DETECT_MODE: H
  checkpoints_path: checkpoints/
  # checkpoints_path: output/ctpn_end2end/voc_2007_trainval
  # 在做nms之前，最多保留的候选box数目
  RPN_PRE_NMS_TOP_N: 12000
  # 做完nms之后，最多保留的box的数目
  RPN_POST_NMS_TOP_N: 2000
  # nms 阈值
  RPN_NMS_THRESH: 0.7
  # 候选box的最小尺寸
  RPN_MIN_SIZE: 8
