# BACKBONE : "VggNet", "InceptionNet"
BACKBONE: "VggNet"
# 16 or 8
ANCHOR_WIDTH: 16
ANCHOR_HEIGHT: [11, 16, 23, 33, 48, 68, 97, 139, 198, 283]
CLASSES_NUM: 2
CLASSES_NAME: ["background", "text"]
USE_GPU_NMS: True
INPUT_NORMALIZATION: "PIXEL_MEANS"
IMG_SCALE: 600
IMG_MAX_SCALE: 1200
USE_GPU_NMS: False
USE_LSTM: True

TRAIN:
  RESTORE: 0
  MAX_STEPS: 100000
  MODEL_SAVE_ITERS: 1000
  # learning rate
  LEARING_RATE_ITERS: 1000
  BEGAIN_LEARNING_RATE: 0.0001
  MIN_LEARNING_RATE: 0.00001
  DISPLAY: 10
  RPN_BATCHSIZE: 300
  GAMMA: 0.1
  MOMENTUM: 0.9
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_NEGATIVE_OVERLAP: 0.3
  RPN_POSITIVE_WEIGHT: -1.0
  RPN_BBOX_INSIDE_WEIGHTS: [0, 1.0, 0, 1.0]
  RPN_CLOBBER_POSITIVES: False
  # 背景和前景的比例
  RPN_FG_FRACTION: 0.5
  FG_FRACTION: 0.3
  WEIGHT_DECAY: 0.0005
  MODEL_OUTPUT_DIR: "./models/train_output/"
  LOGS_DIR: "./logs/"
  PRETRAIN_MODEL: "./models/pretrain_model/VGG_imagenet.npy"
  TRAIN_IMG_DIR: "./data/image/"
  TRAIN_LABEL_DIR: "./data/label/"
  SOLVER: "Adam"
  WITH_CLIP: True

TEST:
  DETECT_MODE: H
  CHECKPOINTS_PATH: ./models/train_output/
  # checkpoints_path: output/ctpn_end2end/voc_2007_trainval
  # 在做nms之前，最多保留的候选box数目
  RPN_PRE_NMS_TOP_N: 12000
  # 做完nms之后，最多保留的box的数目
  RPN_POST_NMS_TOP_N: 2000
  # nms 阈值
  RPN_NMS_THRESH: 0.7
  # 候选box的最小尺寸
  RPN_MIN_SIZE: 16

TEXT:
  MIN_NUM_PROPOSALS: 2
  # PROPOSALS的宽高比
  MIN_RATIO: 0.5
  # 合成后的矩形框得分
  LINE_MIN_SCORE: 0.5
  # 原值50 ,20-30合适
  MAX_HORIZONTAL_GAP: 20
  # 每个PROPOSALS的得分
  TEXT_PROPOSALS_MIN_SCORE: 0.1
  # nms阈值
  TEXT_PROPOSALS_NMS_THRESH: 0.1
  MIN_V_OVERLAPS: 0.7
  MIN_SIZE_SIM: 0.68
  DETECT_MODE: "H"
