# BACKBONE : "VggNet", "InceptionNet"
BACKBONE: "InceptionNet"
ANCHOR_WIDTH: 16
ANCHOR_HEIGHT: [11, 16, 23, 33, 48, 68, 97, 139, 198, 283]
CLASSES_NUM: 2
USE_GPU_NMS: True
INPUT_NORMALIZATION: False
TRAIN:
  restore: 0
  max_steps: 50000
  SOLVER: Adam
  OHEM: False
  RPN_BATCHSIZE: 300
  BATCH_SIZE: 300
  LOG_IMAGE_ITERS: 100
  DISPLAY: 10
  SNAPSHOT_ITERS: 1000
  HAS_RPN: True
  LEARNING_RATE: 0.00001
  MOMENTUM: 0.9
  GAMMA: 0.1
  STEPSIZE: 30000
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
  PRECLUDE_HARD_SAMPLES: True
  BBOX_INSIDE_WEIGHTS: [0, 1, 0, 1]
  RPN_BBOX_INSIDE_WEIGHTS: [0, 1, 0, 1]
  RPN_POSITIVE_WEIGHT: -1.0
  FG_FRACTION: 0.3
  WEIGHT_DECAY: 0.0005
TEST:
  HAS_RPN: True
  DETECT_MODE: H
  checkpoints_path: checkpoints/
  # checkpoints_path: output/ctpn_end2end/voc_2007_trainval
